import { toScaffoldIds } from "./validate";

type TemplateCtx = {
  slug: string;
  displayName: string;
  defaultCategory: string;
  rawCode: string;
  fgCode: string;
  productionScheme: string;
  defaultSaleUnit: string;
  defaultOutputUnit: string;
  defaultOutputPerBase: number;
};

function ids(slug: string) {
  return toScaffoldIds(slug);
}

export function buildScaffoldFiles(ctx: TemplateCtx): Record<string, string> {
  const { slug, displayName, defaultCategory } = ctx;
  const { pascal, upper, constPrefix } = ids(slug);

  return {
    [`src/domains/${slug}/config.ts`]: `/** ${displayName} domain defaults — configuration only, no business logic. */
export const ${constPrefix}_DOMAIN_CONFIG = {
  domain: "${slug}",
  warehouses: {
    rawCode: "${ctx.rawCode}",
    fgCode: "${ctx.fgCode}",
  },
  payroll: {
    productionScheme: "${ctx.productionScheme}",
  },
  product: {
    defaultSaleUnit: "${ctx.defaultSaleUnit}",
    defaultOutputUnit: "${ctx.defaultOutputUnit}",
    defaultCategory: "${defaultCategory}",
    defaultOutputPerBase: ${ctx.defaultOutputPerBase},
  },
} as const;

export type ${pascal}DomainConfig = typeof ${constPrefix}_DOMAIN_CONFIG;
`,

    [`src/domains/${slug}/i18n-overrides.ts`]: `import type { Dict, Locale } from "@core/shared/i18n/i18n";

/** ${displayName} UI terminology layered on top of core i18n. Customize after scaffold. */
export const ${constPrefix}_I18N_OVERRIDES: Record<Locale, Dict> = {
  ru: {
    "products.categoryDefault": "${defaultCategory}",
  },
  tj: {
    "products.categoryDefault": "${defaultCategory}",
  },
};
`,

    [`src/domains/${slug}/help-overrides.ts`]: `import type { Locale } from "@core/shared/i18n/i18n";

type HelpTextOverrides = {
  tour?: Partial<Record<string, string>>;
  faq?: Partial<Record<string, string>>;
};

/** ${displayName} help copy overrides. Customize after scaffold. */
export const ${constPrefix}_HELP_OVERRIDES: Record<Locale, HelpTextOverrides> = {
  ru: {
    tour: {},
    faq: {},
  },
  tj: {
    tour: {},
    faq: {},
  },
};
`,

    [`prisma/seeds/domains/${slug}.ts`]: `import type { PrismaClient } from "@prisma/client";
import { DOMAIN_SETTING_KEYS } from "../../../src/core/config/settings";
import { ${constPrefix}_DOMAIN_CONFIG } from "../../../src/domains/${slug}/config";

export type ${pascal}DomainSeedResult = {
  productionSchemeId: string;
};

/** ${displayName} domain settings + payroll scheme stub. Extend with catalog/opening stock. */
export async function seed${pascal}Domain(prisma: PrismaClient): Promise<${pascal}DomainSeedResult> {
  const domainSettings: Record<string, string> = {
    [DOMAIN_SETTING_KEYS.workshopDomain]: ${constPrefix}_DOMAIN_CONFIG.domain,
    [DOMAIN_SETTING_KEYS.warehouseRawCode]: ${constPrefix}_DOMAIN_CONFIG.warehouses.rawCode,
    [DOMAIN_SETTING_KEYS.warehouseFgCode]: ${constPrefix}_DOMAIN_CONFIG.warehouses.fgCode,
    [DOMAIN_SETTING_KEYS.payrollProductionScheme]: ${constPrefix}_DOMAIN_CONFIG.payroll.productionScheme,
    [DOMAIN_SETTING_KEYS.productDefaultSaleUnit]: ${constPrefix}_DOMAIN_CONFIG.product.defaultSaleUnit,
    [DOMAIN_SETTING_KEYS.productDefaultOutputUnit]: ${constPrefix}_DOMAIN_CONFIG.product.defaultOutputUnit,
    [DOMAIN_SETTING_KEYS.productDefaultCategory]: ${constPrefix}_DOMAIN_CONFIG.product.defaultCategory,
    [DOMAIN_SETTING_KEYS.productDefaultOutputPerBase]: String(
      ${constPrefix}_DOMAIN_CONFIG.product.defaultOutputPerBase,
    ),
  };

  for (const [key, value] of Object.entries(domainSettings)) {
    await prisma.setting.upsert({
      where: { key },
      update: {},
      create: { key, value },
    });
  }

  const prodScheme = await prisma.payScheme.upsert({
    where: { code: ${constPrefix}_DOMAIN_CONFIG.payroll.productionScheme },
    update: { name: "${displayName} production", kind: "PRODUCTION_M2", productionRate: "0" },
    create: {
      code: ${constPrefix}_DOMAIN_CONFIG.payroll.productionScheme,
      name: "${displayName} production",
      kind: "PRODUCTION_M2",
      productionRate: "0",
    },
  });

  return { productionSchemeId: prodScheme.id };
}
`,

    [`prisma/seeds/run-domain-${slug}.ts`]: `import { createSeedClient } from "./client";
import { seed${pascal}Domain } from "./domains/${slug}";

const prisma = createSeedClient();

seed${pascal}Domain(prisma)
  .then(async () => {
    console.log("${pascal} domain seed OK.");
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
`,

    [`src/domains/${slug}/SCAFFOLD.md`]: `# ${displayName} domain scaffold

Generated by \`npm run domain:scaffold -- ${slug}\`.

## Next steps (do not skip)

1. **Register in \`src/domains/registry.ts\`** — add one \`DOMAIN_REGISTRY\` entry (config + i18n + help + seed meta).
2. **Phase 6.4** — Wire env-driven seed orchestrator (\`WORKSHOP_DOMAIN=${slug}\`).
3. Customize \`config.ts\`, i18n/help overrides, and \`prisma/seeds/domains/${slug}.ts\` catalog.
4. Add \`db:seed:domain:${slug}\` script to package.json when registry exists.
5. Run domain seed only after registration: \`tsx prisma/seeds/run-domain-${slug}.ts\`

## Files created

- \`src/domains/${slug}/config.ts\`
- \`src/domains/${slug}/i18n-overrides.ts\`
- \`src/domains/${slug}/help-overrides.ts\`
- \`prisma/seeds/domains/${slug}.ts\`
- \`prisma/seeds/run-domain-${slug}.ts\`

Facade runtime is unchanged until registry registration in \`src/domains/registry.ts\`.
`,
  };
}
